#include "generate.hpp"

#include <fstream>
#include <sstream>

namespace torc {

std::string generate_extdep_mak(const Manifest &m) {
    std::ostringstream out;
    out << "# Auto-generated by torc — do not edit\n";

    std::ostringstream cxx, ld, libs;
    for (const auto &pkg : m.packages()) {
        std::string prefix = m.depdir() + "/" + pkg.name() + "/" + pkg.version();
        cxx << " \\\n    -I" << prefix << "/include";
        ld << " \\\n    -L" << prefix << "/lib";
        libs << " -l" << pkg.lib_name();
    }

    out << "TORC_CXXFLAGS =" << cxx.str() << "\n";
    out << "TORC_LDFLAGS  =" << ld.str() << "\n";
    out << "TORC_LIBS     =" << libs.str() << "\n";

    return out.str();
}

bool write_mak(const std::string &path, const std::string &content) {
    std::ofstream f(path);
    if (!f)
        return false;
    f << content;
    return f.good();
}

} // namespace torc
