#include "localdep.hpp"

#include "yaml.hpp"

#include <fstream>
#include <map>
#include <set>
#include <sstream>

namespace torc {

void for_each_lib_ordered(const LocalDeps &local, const LibOrderVisitor &visitor) {
    // Topological sort (Kahn's algorithm)
    std::map<std::string, const LocalLib *> by_name;
    std::map<std::string, std::set<std::string>> incoming;
    for (const auto &lib : local.libs()) {
        by_name[lib.name()] = &lib;
        incoming[lib.name()]; // ensure entry exists
    }
    for (const auto &lib : local.libs())
        for (const auto &dep : lib.deps())
            incoming[lib.name()].insert(dep);

    std::vector<std::string> queue;
    for (const auto &[name, deps] : incoming)
        if (deps.empty())
            queue.push_back(name);

    while (!queue.empty()) {
        auto cur = queue.back();
        queue.pop_back();
        if (by_name.count(cur))
            visitor(*by_name[cur]);

        for (auto &[name, deps] : incoming) {
            if (deps.erase(cur) && deps.empty())
                queue.push_back(name);
        }
    }
}

std::string generate_localdep_mak(const LocalDeps &local) {
    std::ostringstream out;
    out << "# Auto-generated by torc — local dependencies\n\n";

    // Build order
    out << "LOCALDEP_ORDER =";
    for_each_lib_ordered(local, [&](const LocalLib &lib) { out << " " << lib.dir(); });
    out << "\n\n";

    // Include flags
    out << "LOCALDEP_CXXFLAGS =";
    for (const auto &lib : local.libs()) {
        std::string inc = lib.include().empty() ? lib.dir() + "/include" : lib.include();
        out << " -I" << inc;
    }
    out << "\n";

    // Link flags
    out << "LOCALDEP_LDFLAGS =";
    for (const auto &lib : local.libs())
        out << " -L" << lib.dir() << "/build";
    out << "\n";

    out << "LOCALDEP_LIBS =";
    for (const auto &lib : local.libs())
        out << " -l" << lib.name();
    out << "\n\n";

    // Per-target dependency rules
    for (const auto &lib : local.libs()) {
        if (lib.deps().empty())
            continue;
        out << lib.dir() << "/build/lib" << lib.name() << ".a:";
        for (const auto &dep : lib.deps()) {
            // Find dep's dir
            for (const auto &d : local.libs()) {
                if (d.name() == dep) {
                    out << " " << d.dir() << "/build/lib" << d.name() << ".a";
                    break;
                }
            }
        }
        out << "\n";
    }

    // Binary target deps
    for (const auto &tgt : local.targets()) {
        if (tgt.deps().empty())
            continue;
        out << tgt.dir() << "/build/" << tgt.name() << ":";
        for (const auto &dep : tgt.deps()) {
            for (const auto &lib : local.libs()) {
                if (lib.name() == dep) {
                    out << " " << lib.dir() << "/build/lib" << lib.name() << ".a";
                    break;
                }
            }
        }
        out << "\n";
    }

    return out.str();
}

LocalDeps load_local_deps(const std::string &manifest_path) {
    LocalDeps local;
    std::ifstream f(manifest_path);
    if (!f)
        return local;

    std::ostringstream ss;
    ss << f.rdbuf();
    auto result = yaml::parse(ss.str());
    if (!result.ok() || !result.root.is_map())
        return local;

    auto *loc = result.root.get("local");
    if (!loc || !loc->is_map())
        return local;

    if (auto *libs = loc->get("libs")) {
        if (libs->is_list()) {
            for (const auto &item : libs->as_list()) {
                if (!item.is_map())
                    continue;
                LocalLib lib;
                if (auto *n = item.get("name"))
                    lib.set_name(n->as_scalar());
                if (auto *d = item.get("dir"))
                    lib.set_dir(d->as_scalar());
                if (auto *i = item.get("include"))
                    lib.set_include(i->as_scalar());
                if (auto *deps = item.get("deps")) {
                    if (deps->is_list())
                        for (const auto &d : deps->as_list())
                            if (d.is_scalar())
                                lib.add_dep(d.as_scalar());
                }
                if (!lib.name().empty())
                    local.add_lib(std::move(lib));
            }
        }
    }

    if (auto *targets = loc->get("targets")) {
        if (targets->is_list()) {
            for (const auto &item : targets->as_list()) {
                if (!item.is_map())
                    continue;
                LocalTarget tgt;
                if (auto *n = item.get("name"))
                    tgt.set_name(n->as_scalar());
                if (auto *d = item.get("dir"))
                    tgt.set_dir(d->as_scalar());
                if (auto *deps = item.get("deps")) {
                    if (deps->is_list())
                        for (const auto &d : deps->as_list())
                            if (d.is_scalar())
                                tgt.add_dep(d.as_scalar());
                }
                if (!tgt.name().empty())
                    local.add_target(std::move(tgt));
            }
        }
    }

    return local;
}

} // namespace torc
