#include "scaffold.hpp"
#include "diag.hpp"
#include "exitcodes.hpp"

#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace torc {

namespace fs = std::filesystem;

static bool write_file(const std::string& path, const std::string& content) {
    std::ofstream f(path);
    if (!f) return false;
    f << content;
    return f.good();
}

static std::string makefile_header(const std::string& name) {
    return R"(# Generated by torc — customize freely
CXX       ?= g++
CXXSTD    ?= -std=c++20
WARNINGS  ?= -Wall -Wextra -Werror -pedantic
CXXFLAGS  += $(CXXSTD) $(WARNINGS) -Isrc

# ── torc dependencies ─────────────────────────────
-include extdep.mak
CXXFLAGS += $(TORC_CXXFLAGS)
LDFLAGS  += $(TORC_LDFLAGS)
LDLIBS   += $(TORC_LIBS)

SRC_DIR   = src
BUILD_DIR = build
SRCS      = $(wildcard $(SRC_DIR)/*.cpp)
OBJS      = $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.o,$(SRCS))
TARGET    = $(BUILD_DIR)/)" + name + "\n";
}

static std::string makefile_rules() {
    return R"(
DEPFLAGS  = -MMD -MP

.PHONY: all clean deps

all: $(TARGET)

$(TARGET): $(OBJS) | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

$(BUILD_DIR):
	mkdir -p $@

# Fetch/build external deps and regenerate extdep.mak
deps:
	torc install
	torc generate

clean:
	rm -rf $(BUILD_DIR)

# ── Local header dependencies (auto-generated by -MMD) ──
-include $(OBJS:.o=.d)
)";
}

static std::string makefile_content(const std::string& name) {
    return makefile_header(name) + makefile_rules();
}

static std::string torc_yaml_content() {
    return R"(depdir: ~/.local/share/torc
parallel: 4

packages: []
)";
}

static std::string gitignore_content() {
    return R"(build/
*.o
*.d
extdep.mak
)";
}

static std::string clang_format_content() {
    return R"(BasedOnStyle: LLVM
IndentWidth: 4
ColumnLimit: 100
)";
}

static std::string main_cpp_content([[maybe_unused]] const std::string& name) {
    return R"(#include <cstdio>

int main() {
    std::puts("hello, world");
    return 0;
}
)";
}

static std::string lib_hpp_content(const std::string& name) {
    return "#pragma once\n\nnamespace " + name +
           " {\n\nint version();\n\n} // namespace " + name + "\n";
}

static std::string lib_cpp_content(const std::string& name) {
    return "#include \"" + name + "/" + name +
           ".hpp\"\n\nnamespace " + name +
           " {\n\nint version() { return 1; }\n\n} // namespace " + name + "\n";
}

static std::string test_main_content() {
    return R"(#include <cstdio>
#include <cstdlib>

#define ASSERT(cond) do { \
    if (!(cond)) { \
        std::fprintf(stderr, "FAIL: %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        std::exit(1); \
    } \
} while(0)

int main() {
    ASSERT(1 + 1 == 2);
    std::puts("all tests passed");
    return 0;
}
)";
}

static std::string timestamp_suffix() {
    auto now = std::chrono::system_clock::now();
    auto t = std::chrono::system_clock::to_time_t(now);
    std::ostringstream ss;
    ss << std::put_time(std::localtime(&t), "%Y%m%d-%H%M%S");
    return ss.str();
}

int cmd_new(const NewOpts& opts) {
    if (opts.name().empty()) {
        diag::error("new", "project name required");
        return EX_USAGE;
    }

    if (fs::exists(opts.name())) {
        diag::error("new", "directory already exists: " + opts.name());
        return EX_CANTCREAT;
    }

    std::string base = fs::path(opts.name()).filename().string();
    std::error_code ec;
    fs::create_directories(opts.name() + "/src", ec);
    fs::create_directories(opts.name() + "/tests", ec);
    fs::create_directories(opts.name() + "/include/" + base, ec);

    write_file(opts.name() + "/torc.yaml", torc_yaml_content());
    write_file(opts.name() + "/Makefile", makefile_content(base));
    write_file(opts.name() + "/.gitignore", gitignore_content());
    write_file(opts.name() + "/.clang-format", clang_format_content());

    if (opts.lib()) {
        write_file(opts.name() + "/src/" + base + ".cpp", lib_cpp_content(base));
        write_file(opts.name() + "/include/" + base + "/" + base + ".hpp",
                   lib_hpp_content(base));
    } else {
        write_file(opts.name() + "/src/main.cpp", main_cpp_content(base));
    }

    write_file(opts.name() + "/tests/test_main.cpp", test_main_content());

    if (!opts.no_git()) {
        std::string cmd = "cd '" + opts.name() + "' && git init -q";
        int rc = std::system(cmd.c_str());
        if (rc != 0) diag::error("new", "git init failed");
    }

    diag::info("created project: " + opts.name());
    return EX_OK;
}

int cmd_init(const InitOpts& opts) {
    std::string dir = opts.dir();
    std::string mf = dir + "/Makefile";

    if (fs::exists(mf)) {
        if (!opts.force()) {
            diag::error("init", "Makefile already exists (use --force to overwrite)");
            return EX_CANTCREAT;
        }
        std::string backup = mf + "." + timestamp_suffix() + ".bak";
        std::error_code ec;
        fs::rename(mf, backup, ec);
        if (ec) {
            diag::error("init", "cannot backup Makefile: " + ec.message());
            return EX_IOERR;
        }
        diag::info("backed up Makefile → " + backup);
    }

    std::string name = opts.name();
    if (name.empty()) {
        name = fs::path(fs::absolute(dir)).filename().string();
    }

    if (!write_file(mf, makefile_content(name))) {
        diag::error("init", "failed to write Makefile");
        return EX_IOERR;
    }

    diag::info("wrote " + mf);
    return EX_OK;
}

} // namespace torc
